### ISSUE TITLE
Error: No module named 'ns3gym.messages_pb2'

### ISSUE THREAD

**Issue by huckiyang** [tkn-tub/ns3-gym#1]
Dear ns3-gym team,

really nice work, but I bumped into a problem when I try
**$ env = gym.make('ns3-v0')**
>     import ns3gym.messages_pb2 as pb
> ModuleNotFoundError: No module named 'ns3gym.messages_pb2'
with these error messages and could not empower the env any further. 

I guess the messages_pd2 is this one below, but don't know where shall it be put. 
https://github.com/grpc/grpc/blob/master/test/http2_test/messages_pb2.py

Any suggestion? noted I clone the ns3-gym with the version and followed your read.me just today - 10/22. Cheers

**Comment by pgawlowicz** [comment]
Hi, 

Thank you for pointing out this issue.

The readme file was simply wrong, and I have already fixed it (swapped points 3 and 4).
First, you have to run:
./waf configure
that generates both C++ and Python Protocol Buffer messages and only then you can install python module using:
pip3 install ./src/opengym/model/ns3gym

In addition, I have added some more checks to prevent installing python module without messages_pb2.py file as well as forcing to use protoc compiler in version 3.

Best,
Piotr

**Comment by huckiyang** [comment]
Dear Piotr

thanks for the kind reply, I will try your solution. 
I manually added the messages_pb2.py a few hours ago. 
in the path

>  python3.6/site-packages/ns3gym/

the error message seems to disappear. 
btw, is it take a long while to initiate the gym.make('ns3-v0'), more than 10min?

**Comment by pgawlowicz** [comment]
Hi,
Probably ns3 project is being built during this long time. You should build the project before using:
 ./waf build

If you install the ns3gym python module inside a virtual environment, you have to build ns3 in the same virtual env, using ./waf build

However, the build is done only once and then examples should run immediately.

BR,
Piotr
