### ISSUE TITLE
string: No such file or directory

### ISSUE THREAD

**Issue by 1272652761** [tkn-tub/ns3-gym#10]
When I run the script `./waf build`, it rhrew a exception which is `string: No such file or directory`, but I have installed package `gcc`, `g++` and `build-essential`, how to solve this problem?

**Comment by pgawlowicz** [comment]
Hi,
you have given too little information, so I cannot help you. But I can assure you that the installation procedure was tested many times and was always working, so most probably the issue is on your side. 
Best,
Piotr
