### ISSUE TITLE
Basic example for connnecting ns3-gym with stable-baselines

### ISSUE THREAD

**Issue by H-Park** [tkn-tub/ns3-gym#11]
It would be very convenient to be able to use stable-baselines out of the box on the gym-esque environments in this project. Although the environment's API access mirrors OpenAI's gym, under the hood there are discrepancies that prevent integration with stable-baselines as is.

**Comment by rlan** [comment]
> It would be very convenient to be able to use stable-baselines out of the box on the gym-esque environments in this project. Although the environment's API access mirrors OpenAI's gym, under the hood there are discrepancies that prevent integration with stable-baselines as is.

@H-Park I'm also looking into integrating them. Would you mind sharing what discrepancies you have found so the community could improve it? Thanks!

**Comment by H-Park** [comment]
Now that I think about it, I think this isn't an error on ns3-gym's end, it was an update to gym that caused the breakage, mostly their spaces.

**Comment by sheila-janota** [comment]
Hi @H-Park
I am trying to integrate ns3gym with stable baseline PPO algorithm, but I'm facing some issues when trying to check the new custom environment which I'm creating.
Did had any success when you tried to integrate ns3gym with stable baseline?

Thanks in advance.
