### ISSUE TITLE
Difference between TimeBasedTcp and EventBasedTcp in example/rltcp?

### ISSUE THREAD

**Issue by Hesy-H** [tkn-tub/ns3-gym#13]
Still can not figure out differences between TimeBasedTcp and EventBasedTcp in example/rltcp, which seems no materials I can refer to?

**Comment by pgawlowicz** [comment]
Hi, 

In the TcpTimeStepGymEnv the state of TCP is reported in equal time steps, as the `Notify()` function is scheduled periodically:
https://github.com/tkn-tub/ns3-gym/blob/master/scratch/rl-tcp/tcp-rl-env.cc#L422-L428

While in the TcpEventGymEnv the `Notify()` function is executed every time the TCP instance tries to access or change its internal state.

Best,
Piotr

**Comment by Hesy-H** [comment]
Thanks !
