### ISSUE TITLE
Nothing output when running"test_tcp.py"

### ISSUE THREAD

**Issue by wushilan** [tkn-tub/ns3-gym#21]
I install successfully on Ubuntu,but when I run "test_tcp.py",nothing shows in my terminal.

When I try to build on macOS Catalina ,
Build failed
 -> task in 'ns3-dsr' failed with exit status 1: 
	{task 4350314872: cxx dsr-rsendbuff.cc -> dsr-rsendbuff.cc.1.o}
['/usr/bin/clang++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-unused-local-typedefs', '-Wno-potentially-evaluated-expression', '-std=c++11', '-fPIC', '-Isrc/dsr', '-I../src/dsr', '-I.', '-I..', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_ZMQ=1', '-DHAVE_PROTOBUF=1', '-DHAVE_SQLITE3=1', '../src/dsr/model/dsr-rsendbuff.cc', '-c', '-o/Users/kongyuyang/ns3-gym-master/build/src/dsr/model/dsr-rsendbuff.cc.1.o']
 -> task in 'ns3-dsr' failed with exit status 1: 
	{task 4350315320: cxx dsr-errorbuff.cc -> dsr-errorbuff.cc.1.o}
['/usr/bin/clang++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-unused-local-typedefs', '-Wno-potentially-evaluated-expression', '-std=c++11', '-fPIC', '-Isrc/dsr', '-I../src/dsr', '-I.', '-I..', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_ZMQ=1', '-DHAVE_PROTOBUF=1', '-DHAVE_SQLITE3=1', '../src/dsr/model/dsr-errorbuff.cc', '-c', '-o/Users/kongyuyang/ns3-gym-master/build/src/dsr/model/dsr-errorbuff.cc.1.o']
 -> task in 'ns3-dsr' failed with exit status 1: 
	{task 4350314648: cxx dsr-maintain-buff.cc -> dsr-maintain-buff.cc.1.o}
['/usr/bin/clang++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-unused-local-typedefs', '-Wno-potentially-evaluated-expression', '-std=c++11', '-fPIC', '-Isrc/dsr', '-I../src/dsr', '-I.', '-I..', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_ZMQ=1', '-DHAVE_PROTOBUF=1', '-DHAVE_SQLITE3=1', '../src/dsr/model/dsr-maintain-buff.cc', '-c', '-o/Users/kongyuyang/ns3-gym-master/build/src/dsr/model/dsr-maintain-buff.cc.1.o']

**Comment by wushilan** [comment]
It seems always running this 
env = ns3env.Ns3Env(port=port, stepTime=stepTime, startSim=startSim, simSeed=seed, simArgs=simArgs, debug=debug)

**Comment by LiYufengzz** [comment]
> It seems always running this
> env = ns3env.Ns3Env(port=port, stepTime=stepTime, startSim=startSim, simSeed=seed, simArgs=simArgs, debug=debug)

yes,i have met the same question,my code always stuck in this line.Do you get the solution to this problem?
