### ISSUE TITLE
sim.cc

### ISSUE THREAD

**Issue by llllllllluGquan** [tkn-tub/ns3-gym#26]
hi, when i modified the parameters of sim.cc in tcp-rl. then it show me some errors.

Build ns-3 project if required
Waf: Entering directory `/home/ubuntu/ns3-gym-master/build'
[1819/1880] Compiling scratch/rl-tcp/sim.cc
Waf: Leaving directory `/home/ubuntu/ns3-gym-master/build'

so what shoud i do ?thanks.

**Comment by chwang1996** [comment]
Are you running the python script?
If your ns3 scratch is crash or has compile error, the python script would stuck to wait for the ns3 response.
You can run ./waf --run "rl-tcp" first to check if the ns3 script run successfully, you can also modify the ns3-gym/src/opengym/model/ns3gym/ns3gym/start_sim.py start_sim_script function to output the stderr to file to debug

**Comment by llllllllluGquan** [comment]
> Are you running the python script?
> If your ns3 scratch is crash or has compile error, the python script would stuck to wait for the ns3 response.
> You can run ./waf --run "rl-tcp" first to check if the ns3 script run successfully, you can also modify the ns3-gym/src/opengym/model/ns3gym/ns3gym/start_sim.py start_sim_script function to output the stderr to file to debug

thanks for your replay！
