### ISSUE TITLE
Validation of results from test_tcp.py in ns3-gym

### ISSUE THREAD

**Issue by huckiyang** [tkn-tub/ns3-gym#3]
Dear @pgawlowicz and ns3-gym team,

Just a question and some echos. After successfully running the test_tcp.py, I collected the results from the actions and observation and got the part of the table below to represent TCP-NewReno

 stepIdx | Act_new_cWnd | Act_new_ssThresh | Obs_cWnd | Obs_ssThresh | Info | bytesInFlight | segmentSize | segmentsAcked
-- | -- | -- | -- | -- | -- | -- | -- | --
1 |1 | 18552368 | 340 | 4294967295 | CwndEvent | 37104736 | 340 | 0
2 |1 | 18552368 | 340 | 4294967295 | CongestionStateSet | 37718224 | 340 | 0
3 |1 | 18859112 | 340 | 4294967295 | CwndEvent | 37718224 | 340 | 0
4 |1 | 18859112 | 340 | 4294967295 | PktsAcked | 37104736 | 340 | 1
5 |680 | 18552368 | 340 | 4294967295 | IncreaseWindow | 37104736 | 340 | 1

[CSV flie Here](https://github.com/huckiyang/ns3-gym-plot/blob/master/0out.csv)

Regarding to existing TCP-NewReno in ns-2/ns-3, we shall be able to plot the x = ['simulate time (mms)'], y = ['cwnd'] as below fig in ns-2/ns-3
![Fig ns2-RewReno](https://github.com/huckiyang/ns3-gym-plot/blob/master/ns2_NewReno.png)

Since the results we got for the y-axis is the 'stepIdx' instead of the 'time'
![Fig ns3-gym-RewReno](https://github.com/huckiyang/ns3-gym-plot/blob/master/ns3-gym_NewReno.png) 

As the potential Benchmark for adaptive/learning-based network simulator, is it possible to get the time parameters to compare the existing results as NewReno in ns3-gym? Otherwise, it is still a bit hard to validate the future rl-algorithms on the ns3-gym testbed with existing results in ns-2/ns-3. 

Again many thanks for your amazing works on this research project, :)

**Comment by pgawlowicz** [comment]
I have added simulation timestamp [in ms] to the observations. 
It was easy - see this [commit](https://github.com/tkn-tub/ns3-gym/commit/4a667c5bd2a52f6641126d7818870a95e9de7b3d)

and plese check result in:
[tcp_newreno.py](https://github.com/tkn-tub/ns3-gym/blob/master/scratch/rl-tcp/tcp_newreno.py)

**Comment by huckiyang** [comment]
dear @pgawlowicz yes, it works. Thanks!
I used a topology referring to [Remy](https://github.com/tcpexmachina/remy/blob/master/src/remy.cc)
