### ISSUE TITLE
some problem in ./waf build 

### ISSUE THREAD

**Issue by zlh004** [tkn-tub/ns3-gym#30]
I meet some problem in ./waf build, like following, does anyone help me? Thanks a lot.
![TIM截图20200609161505](https://user-images.githubusercontent.com/38122569/84123455-6ff8fd00-aa6c-11ea-9686-c417c924f0f0.png)
Build failed
 -> task in 'ns3-opengym' failed with exit status 1 (run with -v to display more information)

**Comment by pgawlowicz** [comment]
please try to clone and build the project again.

**Comment by zlh004** [comment]
can i beg the details? does it means clone 'ns3-gym-master' to another folder, then build it again?
(p.s, i build it in virtualbox ubuntu 20.04, what's the impact of this?)
thanks a lot

**Comment by pgawlowicz** [comment]
yep, just pull new code and build it again

**Comment by zlh004** [comment]
i tried it, but it didn't seem to work. 
is there any other way to solve this problem please?
thank u all the same

**Comment by pgawlowicz** [comment]
did you clean the project using:
`./waf clean`

are you sure that you have checked out the last commit?

**Comment by zlh004** [comment]
it means using './waf clean' after clone, then build it again? 
let me have a try, thank u

**Comment by zlh004** [comment]
i didn't notice the last commit either

**Comment by zlh004** [comment]
yesterday's network is not very good, after downloading the file today, the problem has been solved
thank u

**Comment by ChloeInSpring** [comment]
I have the same problem today. Could you explain in detail how to solve it?  Looking forward to your reply. Thank u

> yesterday's network is not very good, after downloading the file today, the problem has been solved thank u

**Comment by yntao-hust** [comment]
@zlh004 @pgawlowicz 
Hello, I also meet the same problem as above, and try to solve it by following the guide in the dialogue above, but it doesn't work.
I restate the detail:
1. clone the folder 'ns3-gym-master', maybe we name it 'ns3-gym-master-plus'.
2. enter the directory 'ns3-gym-master-plus'.
3. execute the command './waf configure'.
4. execute the command './waf clean' and './waf build' respectively.

Is it correct? I follow the steps but it still doesn't work. Any other method, or is there something wrong with my steps?
Tks a lot. 
Regards

**Comment by pgawlowicz** [comment]
Hi @yntao-hust 
I believe that the repo has to be cloned into `opengym` directory:
```
git clone https://github.com/tkn-tub/ns3-gym.git ./opengym
```
BR, Piotr
