### ISSUE TITLE
No opengym module after ./waf configure and build

### ISSUE THREAD

**Issue by PennyXQZ** [tkn-tub/ns3-gym#42]
Modules built:
antenna                   aodv                      applications
bridge                    buildings                 config-store
core                      csma                      csma-layout
dsdv                      dsr                       energy
fd-net-device             flow-monitor              internet
internet-apps             lr-wpan                   lte
mesh                      mobility                  mpi
netanim (no Python)       network                   nix-vector-routing
olsr                      point-to-point            point-to-point-layout
propagation               sixlowpan                 spectrum
stats                     tap-bridge                test (no Python)
topology-read             traffic-control           uan
virtual-net-device        visualizer                wave
wifi                      wimax

Modules not built (see ns-3 tutorial for explanation):
brite                     click                     openflow

After conduct ./waf configure and ./waf build, the opengym module doesn't show either in module-built area or in module-not-built area. Why dose this happen? I have tried many times. Please give me some suggestions. Thanks!

**Comment by PhilYang09** [comment]
How to solve the problem? I run to the same problem now. Thanks

**Comment by pgawlowicz** [comment]
you should not use waf in the newest ns-3 version. Please follow the installation tutorial in readme for ns-3.36+ versions.
