### ISSUE TITLE
sum reward is 0 

### ISSUE THREAD

**Issue by HamidYgn** [tkn-tub/ns3-gym#62]
Hi,
I ran the Agent_test.py many times but the Agent doesn't receive any reward and After type ./waf --run "rl-tcp --transport_prot=TcpRlTimeBased" the seed value is 0.
How can I fix it?
Thanks in Advance,

-Hamid

<img width="609" alt="174723905-a6dffc0e-d1e8-4ef5-b476-5acf7825f6f3" src="https://user-images.githubusercontent.com/101704061/174846588-475019df-ba4e-41a4-b80c-e7e60f972ae9.png">

**Comment by 862284484** [comment]
> 嗨， 我多次运行 Agent_test.py 但代理没有收到任何奖励并输入 ./waf --run "rl-tcp --transport_prot=TcpRlTimeBased" 后种子值为 0。我该如何理解决？提前 致谢 ，
> 
> -哈米德
> 
> <img alt="174723905-a6dffc0e-d1e8-4ef5-b476-5acf7825f6f3" width="609" src="https://user-images.githubusercontent.com/101704061/174846588-475019df-ba4e-41a4-b80c-e7e60f972ae9.png">

how to solve
