### ISSUE TITLE
Updating port to ns-3.36.1

### ISSUE THREAD

**Issue by rukyr97** [tkn-tub/ns3-gym#66]
Hello... the current release is not working for the most recent version of ns-3 (ns-3.36.1) 
Any guidelines on what is needed to update? I hope it is something minor :)

**Comment by rukyr97** [comment]
*The error stack for ./ns3 configure*

`~/ns-allinone-3.36.1/ns-3.36.1$ ./ns3 configure
-- Using default output directory /home/rmq/ns-allinone-3.36.1/ns-3.36.1/build
-- Proceeding without cmake-format
-- find_external_library: SQLite3 was not found. Missing headers: "sqlite3.h" and missing libraries: "sqlite3".
-- SQLite was not found
-- Harfbuzz is required by GTK3 and was not found.
-- LibXML2 was not found. Continuing without it.
-- LibRT was found.
-- Visualizer requires Python bindings
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- GSL was not found. Continuing without it.
-- docs: doxygen documentation not enabled due to missing dependencies: doxygen;dot;dia
-- docs: sphinx documentation not enabled due to missing dependencies: epstopdf;pdflatex;latexmk;convert;dvipng
-- Precompiled headers were enabled
-- Processing contrib/opengym
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- pkgconf not found
-- Processing src/antenna
-- Processing src/aodv
-- Processing src/applications
-- Processing src/bridge
-- Processing src/brite
-- find_external_library: brite was not found. Missing headers: "Brite.h" and missing libraries: "brite".
-- Skipping src/brite
-- Processing src/buildings
-- Processing src/click
-- find_external_library: click was not found. Missing headers: "simclick.h" and missing libraries: "nsclick;click".
-- Skipping src/click
-- Processing src/config-store
-- Processing src/core
-- Boost Units are an optional feature of length.cc.; Ubuntu ships it within the libboost-dev package.; You may need to clean up the CMake cache after installing it to pass this check.
-- Processing src/csma
-- Processing src/csma-layout
-- Processing src/dsdv
-- Processing src/dsr
-- Processing src/energy
-- Processing src/fd-net-device
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Processing src/flow-monitor
-- Processing src/internet
-- Processing src/internet-apps
-- Processing src/lr-wpan
-- Processing src/lte
-- Processing src/mesh
-- Processing src/mobility
-- Processing src/netanim
-- Processing src/network
-- Processing src/nix-vector-routing
-- Processing src/olsr
-- Processing src/openflow
-- find_external_library: openflow was not found. Missing headers: "openflow.h" and missing libraries: "openflow".
-- Skipping src/openflow
-- Processing src/point-to-point
-- Processing src/point-to-point-layout
-- Processing src/propagation
-- Processing src/sixlowpan
-- Processing src/spectrum
-- Processing src/stats
-- Processing src/tap-bridge
-- Processing src/test
-- Processing src/topology-read
-- Processing src/traffic-control
-- Processing src/uan
-- Processing src/virtual-net-device
-- Processing src/wave
-- Processing src/wifi
-- Processing src/wimax
-- ---- Summary of optional ns-3 features:
Build profile                 : default
Build directory               : /home/rmq/ns-allinone-3.36.1/ns-3.36.1/build
BRITE Integration             : OFF (missing dependency)
DES Metrics event collection  : OFF (not requested)
DPDK NetDevice                : OFF (not requested)
Emulation FdNetDevice         : ON
Examples                      : OFF (not requested)
File descriptor NetDevice     : ON
GNU Scientific Library (GSL)  : OFF (missing dependency)
GtkConfigStore                : OFF (missing dependency)
LibXml2 support               : OFF (missing dependency)
MPI Support                   : OFF (not requested)
ns-3 Click Integration        : OFF (missing dependency)
ns-3 OpenFlow Integration     : OFF (missing dependency)
Netmap emulation FdNetDevice  : OFF (missing dependency)
PyViz visualizer              : OFF (missing dependency)
Python API Scanning Support   : OFF (not requested)
Python Bindings               : OFF (not requested)
Real Time Simulator           : ON
SQLite support                : OFF (missing dependency)
Tap Bridge                    : ON
Tap FdNetDevice               : ON
Tests                         : OFF (not requested)


Modules configured to be built:
antenna                   aodv                      applications
bridge                    buildings                 config-store
core                      csma                      csma-layout
dsdv                      dsr                       energy
fd-net-device             flow-monitor              internet
internet-apps             lr-wpan                   lte
mesh                      mobility                  netanim
network                   nix-vector-routing        olsr
point-to-point            point-to-point-layout     propagation
sixlowpan                 spectrum                  stats
tap-bridge                topology-read             traffic-control
uan                       virtual-net-device        wave
wifi                      wimax

Modules that cannot be built:
brite                     click                     mpi
openflow                  opengym                   test
visualizer
`

**Comment by Gabrielcarvfer** [comment]
Install pkg-config and it should work.

**Comment by rukyr97** [comment]
> Install pkg-config and it should work.

Thank you... it did work! I sent a merge request to update the README file with this note.
