### ISSUE TITLE
I can't change nodeNum where I run the example of qlearn.py

### ISSUE THREAD

**Issue by hzr1140521792** [tkn-tub/ns3-gym#8]
When I change the nodeNum in the code,I get nothing but this 
![image](https://user-images.githubusercontent.com/18465083/49873142-1f441c00-fe56-11e8-9ab9-2c51a73e522f.png)
My environment is :Ubuntu 16.04 and Python3
Thanks very much

**Comment by pgawlowicz** [comment]
Hi, 

The `dqn-agent-v1.py` is not generic and will work only with 5 nodes. If you change the node number to 6, then the action vector should contain 6 values , but in a current version, it still sends a vector with 5 elements.

You can simply extend it to more nodes or make it more generic - i.e. independent of the number of nodes.

The `linear-mesh` ns3 simulation script is generic. To test it please play with `no_op2.py` that is independent of number of nodes, i.e. you can change it easily. 

Best, 
Piotr

**Comment by hzr1140521792** [comment]
I got it,thank you very much.

**Comment by hzr1140521792** [comment]
But I hava another question.Did write all of your param of environment in the file `sim.cc`,but how
can you use it by python,these code are written by C++?

**Comment by pgawlowicz** [comment]
This part of the code allows you to pass command line arguments to the ns-3 process, that will be started by ns3gym. Of course those command line parameters has to be parsed correctly in `sim.cc`:

    simArgs = {"--simTime": simTime,
           "--testArg": 123,
           "--nodeNum": 5,
           "--distance": 500}

    env = ns3env.Ns3Env(port=port, stepTime=stepTime, startSim=startSim, simSeed=seed, simArgs=simArgs, debug=debug)

**Comment by hzr1140521792** [comment]
OK,I got it.Thank you very much.
