### ISSUE TITLE
Missing header messages.pb.h for opengym 

### ISSUE THREAD

**Issue by sv1ple** [tkn-tub/ns3-gym#81]
Dear all,

I am following the instructions to install the branch "_app-ns-3.36+_" with _ns3-38._
When running "_./ns3 configure --enable-examples_", I get the following error:

```
m@DESKTOP-CD:~/ns-3-dev-git$ ./ns3 configure --enable-examples
-- Using default output directory /home/m/ns-3-dev-git/build
-- Proceeding without cmake-format
-- find_external_library: SQLite3 was found.
-- Harfbuzz is required by GTK3 and was not found.
-- LibXML2 was found.
-- Visualizer requires Python bindings
-- GSL was not found. Continuing without it.
-- docs: sphinx documentation not enabled due to missing dependencies: epstopdf latexmk
-- Precompiled headers were enabled
-- Processing contrib/opengym
CMake Error at build-support/3rd-party/colored-messages.cmake:82 (_message):
  Missing header files for opengym:
  ../../cmake-cache/contrib/opengym/messages.pb.h
Call Stack (most recent call first):
  build-support/custom-modules/ns3-module-macros.cmake:266 (message)
  contrib/opengym/CMakeLists.txt:55 (build_lib)


-- Configuring incomplete, errors occurred!
See also "/home/m/ns-3-dev-git/cmake-cache/CMakeFiles/CMakeOutput.log".
See also "/home/m/ns-3-dev-git/cmake-cache/CMakeFiles/CMakeError.log".
Finished executing the following commands:
cd cmake-cache; /usr/bin/cmake -DNS3_EXAMPLES=ON .. ; cd ..
```

Is there any insight regarding the missing "messages.pb.h" file?

Thank you

**Comment by pgawlowicz** [comment]
Hi, could you try a fresh install with the newest version? Thanks!

**Comment by mchristopoulou** [comment]
Hi; apologies for the late reply. I was traveling.

It works in Ubuntu 20.04.6 TLS + ns-3.38 and the latest version of the app-ns-3.36+ (with the changes made three weeks ago).

Just so you know, I had eventually compiled ns3-gym by following the instructions here: https://github.com/tkn-tub/ns3-gym/pull/74 while compiling the protocol buffers manually. But then I left, and this task remained stalled.

In any case, your changes in the branch solve the issue. I manage to run "simple_test.py" successfully.

Thank you
